### ISSUE TITLE
[Bug] Middle mouse release event were submitted twice while not in Ableton

### ISSUE THREAD

**Issue by lueo** [LiveEnhancementSuite/LESforWindows#11] opened 2021-06-30 16:46 UTC
**Describe the bug**
When not in Ableton, the middle mouse release event were submitted twice.

**To Reproduce**
1. Enable LES
2. Open a Google Chrome browser
3. Open a mouse debugger page: https://codepen.io/Streetproject/pen/RgqXeV
4. Click the middle mouse and release
5. The debugger shows two release event

**Expected behavior**
The middle mouse release evnet should only be submitted once if it was clicked once.

**Screenshots**
![middlemouserelease_twice](https://user-images.githubusercontent.com/950423/123999924-9f770080-da05-11eb-8821-e0eca0a1e9ec.png)

**Desktop (please complete the following information):**
 - OS:  Windows 10 20H2
 - Ableton: Live 11.0.2 Suite
 - Mouse: Cosair Harpoon RGB gaming mouse

**Additional context**
none.

**Comment by Kiefy** [comment] 2021-09-02 22:45
This actually causes middle-clicked bookmarks (only in drop-down folders) to open 2 tabs instead of 1 in Chrome.

I was able to fix it by removing this else block:
![](https://i.imgur.com/vzp4FwQ.png)

I have no idea if this is the correct way to apply the fix but I can confirm that MMB panning still works in Ableton, and I no longer get double tabs in chrome. 👍

**Comment by Inversil** [comment] 2021-09-17 10:42
Oh! interesting; thank you for your detailed bug report!! This does need to be fixed. 

There was a problem for a goood while where using middle click to pan would cause keys to get stuck after switching programs https://github.com/LiveEnhancementSuite/LESforWindows/issues/5 and https://github.com/Inversil/LESwin/issues/2, so I added this as a safeguard. Removing that codeblock might cause the bug to come back, but if it hasn't done so for you it may have become redundant. 

I will do the same and test it for a bit and report back my findings.

**Comment by Inversil** [comment] 2021-11-25 15:47
I've been using it this way for a few months now, it's removed in the latest release and it's perfect; should be fixed now!

**Closed as completed by Inversil** 2021-11-25 15:47 UTC
Labels: bug

**Comment by tilse** [comment] 2022-11-01 13:05
i think you might've patched it back in if it was removed at some point because it's still in the script in the latest version and causes that same issue for me
